name: Run PyTest with Coverage

on:
  push:
    branches:
      - main
      - pytest-ci
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -f Dockerfile.minimal -t acr .

    - name: Start docker image (background)
      run: docker run -t -d acr

    # Due to diffuculties with `conda activate` in docker, we do `conda run` while specifying the environment
    - name: Run PyTest with Coverage (inside docker)
      run: docker exec $(docker ps -lq) conda run --no-capture-output -n auto-code-rover pytest --cov=app test/