name: Run PyTest with Coverage

on:
  push:
    branches:
      - main
      - pytest-ci
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: auto-code-rover
          python-version: 3.10
          auto-update-conda: true

      - name: Set PYTHONPATH
        # Mimic the Dockerfile's ENV setting
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install tox
        # Install tox inside the conda environment
        run: conda install -y tox

      - name: Run tox tests
        run: tox -e py

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
