name: Run PyTest with Coverage

on:
  push:
    branches:
      - main
      - pytest-ci
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build docker image
      run: docker build -f Dockerfile.minimal -t acr .

    - name: Start docker image (interactive)
      run: docker run -it acr

    - name: Activate environment
      run: conda activate auto-code-rover

    - name: Run PyTest with Coverage
      run: pytest --cov=app test/